//! Task 10 (2FA backend plan) — end-to-end integration suite for the TOTP
//! 2FA flow: forced enrollment, enroll/verify, login challenge, replay
//! rejection, lockout, backup codes, the no-2FA fast path, and the
//! purpose-token/access-token boundary.
//!
//! Every test drives the REAL HTTP surface (`support::router`, the same
//! `AppState`/`build_router` production wiring the other dashboard suites
//! use) against a fresh `#[sqlx::test]` Postgres database — no mocking of
//! `user_repo`, `totp`, or the handlers themselves. TOTP codes are computed
//! independently via the `totp-rs` crate directly (not via
//! `secureprompt_api::auth::totp`'s private `#[cfg(test)]` `code_at` helper,
//! which is internal to that module) against the `secret_b32` the `/enroll`
//! response returns — so a passing test proves the server's `verify_code`
//! genuinely accepts a code generated by an independent RFC 6238
//! implementation, not merely a fixture the server also produced.
//!
//! Requires a reachable Postgres (`DATABASE_URL`) AND Redis (`REDIS_URL`,
//! defaults to `redis://localhost:6379`) — `docker compose up -d postgres
//! redis`. Also requires `KMS_FILE_KEY` (see `.env`) since `/2fa/enroll`
//! encrypts the TOTP secret via `AppState.kms` before persisting it.

mod support;

use argon2::{
    password_hash::{rand_core::OsRng, PasswordHasher, SaltString},
    Argon2,
};
use axum::{
    body::{to_bytes, Body},
    http::{Request, StatusCode},
    response::Response,
    Router,
};
use chrono::{DateTime, Utc};
use serde_json::{json, Value};
use sqlx::{PgPool, Row};
use totp_rs::{Algorithm, Secret, TOTP};
use tower::ServiceExt;
use uuid::Uuid;

// ---------- Harness ----------

const PASSWORD: &str = "twofactor-test-password-1234";

/// A freshly seeded workspace + single user with a known plaintext password
/// (`PASSWORD`). Every scenario gets its own account (fresh UUIDs + a
/// unique email) so scenarios never share lockout/replay state even when
/// they run in the same test binary.
struct SeededAccount {
    #[allow(dead_code)] // kept for tests that assert on it explicitly
    workspace_id: Uuid,
    user_id: Uuid,
    email: String,
}

fn hash_password(plaintext: &str) -> String {
    let salt = SaltString::generate(&mut OsRng);
    Argon2::default()
        .hash_password(plaintext.as_bytes(), &salt)
        .expect("argon2 hash must succeed with a valid salt")
        .to_string()
}

/// Seed a workspace + one user with `role` and `PASSWORD` directly via SQL
/// (mirrors `tests/dashboard/fixtures.rs::seed_unique_workspace` — the
/// established pattern for this codebase) rather than going through
/// `POST /v1/auth/register`, which always creates an `owner`. Task 10's
/// scenarios need `admin` (2FA-required) and `viewer` (2FA-optional) rows.
async fn seed_account(pool: &PgPool, role: &str) -> sqlx::Result<SeededAccount> {
    let workspace_id = Uuid::new_v4();
    let user_id = Uuid::new_v4();
    let email = format!("{role}-{}@example.com", Uuid::new_v4().simple());
    let password_hash = hash_password(PASSWORD);

    sqlx::query(
        "INSERT INTO workspaces (id, name, created_at, updated_at)
         VALUES ($1, $2, NOW(), NOW())",
    )
    .bind(workspace_id)
    .bind(format!("workspace-{workspace_id}"))
    .execute(pool)
    .await?;

    sqlx::query(
        "INSERT INTO users (id, workspace_id, email, password_hash, role, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, NOW(), NOW())",
    )
    .bind(user_id)
    .bind(workspace_id)
    .bind(&email)
    .bind(&password_hash)
    .bind(role)
    .execute(pool)
    .await?;

    Ok(SeededAccount {
        workspace_id,
        user_id,
        email,
    })
}

async fn read_json(response: Response) -> (StatusCode, Value) {
    let status = response.status();
    let body = to_bytes(response.into_body(), 1 << 20)
        .await
        .expect("read body");
    let value: Value = if body.is_empty() {
        Value::Null
    } else {
        serde_json::from_slice(&body).expect("JSON body")
    };
    (status, value)
}

async fn post_json(
    router: &Router,
    path: &str,
    body: Value,
    bearer: Option<&str>,
) -> (StatusCode, Value) {
    let mut builder = Request::builder()
        .method("POST")
        .uri(path)
        .header("content-type", "application/json");
    if let Some(token) = bearer {
        builder = builder.header("authorization", format!("Bearer {token}"));
    }
    let request = builder
        .body(Body::from(body.to_string()))
        .expect("valid request");
    let response = router.clone().oneshot(request).await.expect("router runs");
    read_json(response).await
}

/// `GET` a protected route with a bearer token, returning only the status —
/// scenario 8 only needs to prove 401 vs not-401, never the body.
async fn get_status_with_bearer(router: &Router, path: &str, bearer: &str) -> StatusCode {
    let request = Request::builder()
        .method("GET")
        .uri(path)
        .header("authorization", format!("Bearer {bearer}"))
        .body(Body::empty())
        .expect("valid request");
    router
        .clone()
        .oneshot(request)
        .await
        .expect("router runs")
        .status()
}

async fn login(router: &Router, email: &str) -> (StatusCode, Value) {
    post_json(
        router,
        "/v1/auth/token",
        json!({"email": email, "password": PASSWORD}),
        None,
    )
    .await
}

// ---------- TOTP code generation (independent of secureprompt_api::auth::totp) ----------

/// Build a `totp_rs::TOTP` for `secret_b32` with the exact RFC 6238 params
/// the server uses (SHA1 / 6 digits / 30s step — see
/// `secureprompt_api::auth::totp::build_totp_checked`), but via a fresh
/// `TOTP::new` call in THIS crate, independent of the server's internal
/// helper (which is private/`#[cfg(test)]`-gated and not reachable from an
/// external integration test binary).
fn build_verifier(secret_b32: &str) -> TOTP {
    let secret_bytes = Secret::Encoded(secret_b32.to_string())
        .to_bytes()
        .expect("enroll response must return a valid base32 secret");
    TOTP::new(Algorithm::SHA1, 6, 0, 30, secret_bytes, None, String::new())
        .expect("valid TOTP parameters")
}

fn unix_now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("system clock after epoch")
        .as_secs()
}

/// The code the server's `verify_code` must currently accept.
fn totp_code_now(secret_b32: &str) -> String {
    build_verifier(secret_b32).generate(unix_now())
}

/// A code that is guaranteed to fall well outside the ±1 timestep (30s)
/// skew window `verify_code` allows (1 hour away), for exercising the
/// failure/lockout paths without any chance of accidentally colliding with
/// a currently-valid code.
fn totp_code_wrong(secret_b32: &str) -> String {
    build_verifier(secret_b32).generate(unix_now().saturating_sub(3600))
}

/// Compute a code guaranteed NOT to collide with whatever timestep is
/// already persisted in `users.totp_last_timestep` for `user_id` (read
/// directly from Postgres).
///
/// Needed wherever a test needs a second, genuinely-DISTINCT successful
/// TOTP use after a first one (e.g. enroll's `/verify` call, then a later
/// `/challenge` call) — the whole round trip in these tests runs in well
/// under 30 seconds, so two back-to-back `totp_code_now` calls land in the
/// SAME RFC 6238 timestep and return the byte-identical code. `verify_code`
/// would then (correctly, per its documented replay-prevention contract)
/// reject the second submission as a replay of the step the first call
/// already consumed — that is real replay protection working as designed,
/// not a bug, but it makes `totp_code_now` alone unsuitable for a second
/// "this must succeed" call within the same test. This helper reads the
/// persisted watermark and steps strictly past it (or uses "now" if "now"
/// is already past it), so the returned code is always fresh.
async fn fresh_totp_code(pool: &PgPool, user_id: Uuid, secret_b32: &str) -> String {
    let row = sqlx::query("SELECT totp_last_timestep FROM users WHERE id = $1")
        .bind(user_id)
        .fetch_one(pool)
        .await
        .expect("fetch totp_last_timestep");
    let last_timestep: Option<i64> = row.get("totp_last_timestep");
    let now_step = i64::try_from(unix_now() / 30).unwrap_or(i64::MAX);
    let step = match last_timestep {
        Some(last) if last >= now_step => last + 1,
        _ => now_step,
    };
    let step_time = u64::try_from(step).unwrap_or(0) * 30;
    build_verifier(secret_b32).generate(step_time)
}

// ---------- Shared enroll+confirm setup (scenarios 3-6, 8 build on this) ----------

/// Drive scenario 2 end-to-end (forced enrollment -> `/enroll` -> `/verify`)
/// and return `(secret_b32, backup_codes)` so later scenarios can compute
/// valid codes / present backup codes against the now-CONFIRMED account.
/// Panics (via `assert_eq!`) on any unexpected status — every caller is
/// itself a `#[sqlx::test]`, so a panic here fails that specific test with
/// a clear message rather than silently cascading.
async fn enroll_and_confirm(router: &Router, account: &SeededAccount) -> (String, Vec<String>) {
    let (status, body) = login(router, &account.email).await;
    assert_eq!(
        status,
        StatusCode::ACCEPTED,
        "setup: forced enrollment must be offered: body={body}"
    );
    let enrollment_token = body["enrollment_token"]
        .as_str()
        .expect("enrollment_token")
        .to_owned();

    let (status, enroll_body) = post_json(
        router,
        "/v1/auth/2fa/enroll",
        json!({}),
        Some(&enrollment_token),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "setup: enroll failed: body={enroll_body}");
    let secret = enroll_body["secret_b32"]
        .as_str()
        .expect("secret_b32")
        .to_owned();
    let backup_codes: Vec<String> = enroll_body["backup_codes"]
        .as_array()
        .expect("backup_codes array")
        .iter()
        .map(|v| v.as_str().expect("backup code string").to_owned())
        .collect();

    let code = totp_code_now(&secret);
    let (status, verify_body) = post_json(
        router,
        "/v1/auth/2fa/verify",
        json!({"code": code}),
        Some(&enrollment_token),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "setup: verify failed: body={verify_body}");
    assert!(verify_body["access_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));

    (secret, backup_codes)
}

// ================================================================
// Scenario 1: forced enrollment on first login for a 2FA-required role.
// ================================================================

#[sqlx::test]
async fn admin_login_returns_forced_enrollment_not_access(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool);

    let (status, body) = login(&router, &account.email).await;

    assert_eq!(status, StatusCode::ACCEPTED, "body={body}");
    assert_eq!(body["enroll_required"], true);
    assert!(body["enrollment_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));
    assert!(
        body.get("access_token").is_none(),
        "forced enrollment must NOT also carry an access token: body={body}"
    );
    assert!(
        body.get("refresh_token").is_none(),
        "forced enrollment must NOT also carry a refresh token: body={body}"
    );
    Ok(())
}

// ================================================================
// Scenario 2: enroll -> verify with a computed code -> access/refresh,
// and totp_confirmed_at is persisted.
// ================================================================

#[sqlx::test]
async fn enroll_then_verify_issues_access_and_confirms_totp(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool.clone());

    let (_secret, backup_codes) = enroll_and_confirm(&router, &account).await;
    assert_eq!(
        backup_codes.len(),
        10,
        "enroll must return exactly 10 backup codes"
    );

    let row = sqlx::query("SELECT totp_confirmed_at FROM users WHERE id = $1")
        .bind(account.user_id)
        .fetch_one(&pool)
        .await?;
    let confirmed_at: Option<DateTime<Utc>> = row.get("totp_confirmed_at");
    assert!(
        confirmed_at.is_some(),
        "totp_confirmed_at must be set once verify() succeeds"
    );
    Ok(())
}

// ================================================================
// Scenario 3: once enrolled, every subsequent login is challenged, and a
// valid code at /challenge yields access/refresh.
// ================================================================

#[sqlx::test]
async fn second_login_issues_challenge_then_a_valid_code_succeeds(
    pool: PgPool,
) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool.clone());
    let (secret, _backup_codes) = enroll_and_confirm(&router, &account).await;

    let (status, body) = login(&router, &account.email).await;
    assert_eq!(status, StatusCode::ACCEPTED, "body={body}");
    assert_eq!(body["twofa_required"], true);
    let challenge_token = body["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();

    // `fresh_totp_code`, not `totp_code_now`: enrollment's `/verify` call
    // just consumed a timestep, and this whole flow runs well under 30s, so
    // "now" may still be the same RFC 6238 step already recorded.
    let code = fresh_totp_code(&pool, account.user_id, &secret).await;
    let (status, challenge_body) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": code}),
        Some(&challenge_token),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "body={challenge_body}");
    assert!(challenge_body["access_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));
    assert!(challenge_body["refresh_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));
    Ok(())
}

// ================================================================
// Scenario 4: replaying the SAME accepted code at /challenge is rejected.
// ================================================================

#[sqlx::test]
async fn challenge_rejects_a_replayed_code(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool.clone());
    let (secret, _backup_codes) = enroll_and_confirm(&router, &account).await;

    let (_status, body) = login(&router, &account.email).await;
    let challenge_token = body["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();
    // `fresh_totp_code`, not `totp_code_now` — see its doc comment: this
    // must be a NEW successful use (distinct from the one `/verify` already
    // consumed during enrollment) so the FIRST /challenge call below
    // genuinely succeeds, making the SECOND (replayed) call the only
    // rejected one — otherwise this test would trivially "pass" for the
    // wrong reason (the first call already being an accidental replay).
    let code = fresh_totp_code(&pool, account.user_id, &secret).await;

    let (status, first) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": code}),
        Some(&challenge_token),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "first use must succeed: body={first}");

    // Same (still-unexpired, 5-min) challenge_token, same code — the code's
    // timestep was persisted by `record_totp_success` on the first call, so
    // `verify_code` must now reject it as replayed.
    let (status, second) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": code}),
        Some(&challenge_token),
    )
    .await;
    assert_eq!(
        status,
        StatusCode::UNAUTHORIZED,
        "replay of the same code must be rejected: body={second}"
    );
    Ok(())
}

// ================================================================
// Scenario 5: 5 bad codes lock the account; a subsequently-correct code is
// still rejected (429) while the lock is active.
// ================================================================

#[sqlx::test]
async fn challenge_locks_account_after_five_bad_codes(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool.clone());
    let (secret, _backup_codes) = enroll_and_confirm(&router, &account).await;

    let (_status, body) = login(&router, &account.email).await;
    let challenge_token = body["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();

    let wrong = totp_code_wrong(&secret);
    for attempt in 1..=5 {
        let (status, resp) = post_json(
            &router,
            "/v1/auth/2fa/challenge",
            json!({"code": wrong}),
            Some(&challenge_token),
        )
        .await;
        assert_eq!(
            status,
            StatusCode::UNAUTHORIZED,
            "bad-code attempt {attempt} must 401: body={resp}"
        );
    }

    // 6th attempt with a genuinely VALID code — must still be locked out.
    let valid = totp_code_now(&secret);
    let (status, resp) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": valid}),
        Some(&challenge_token),
    )
    .await;
    assert_eq!(
        status,
        StatusCode::TOO_MANY_REQUESTS,
        "account must stay locked even with a correct code: body={resp}"
    );

    let row = sqlx::query("SELECT totp_failed_attempts, totp_locked_until FROM users WHERE id = $1")
        .bind(account.user_id)
        .fetch_one(&pool)
        .await?;
    let failed_attempts: i32 = row.get("totp_failed_attempts");
    let locked_until: Option<DateTime<Utc>> = row.get("totp_locked_until");
    assert_eq!(failed_attempts, 5, "5 failures must be recorded, not 6");
    assert!(
        locked_until.is_some_and(|until| until > Utc::now()),
        "totp_locked_until must be set in the future"
    );
    Ok(())
}

// ================================================================
// Scenario 6: a backup code works once at /challenge; reusing it fails.
// ================================================================

#[sqlx::test]
async fn backup_code_is_single_use(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool);
    let (_secret, backup_codes) = enroll_and_confirm(&router, &account).await;
    let backup_code = backup_codes
        .first()
        .expect("at least one backup code")
        .clone();

    let (_status, body) = login(&router, &account.email).await;
    let challenge_token = body["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();

    let (status, resp) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": backup_code}),
        Some(&challenge_token),
    )
    .await;
    assert_eq!(status, StatusCode::OK, "backup code must be accepted: body={resp}");

    // Fresh login -> fresh challenge_token -> the SAME backup code must now
    // be rejected regardless of which challenge_token presents it (the
    // usage is tracked on the backup-code row itself, not the token).
    let (_status2, body2) = login(&router, &account.email).await;
    let challenge_token_2 = body2["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();

    let (status2, resp2) = post_json(
        &router,
        "/v1/auth/2fa/challenge",
        json!({"code": backup_code}),
        Some(&challenge_token_2),
    )
    .await;
    assert_eq!(
        status2,
        StatusCode::UNAUTHORIZED,
        "reusing a consumed backup code must be rejected: body={resp2}"
    );
    Ok(())
}

// ================================================================
// Scenario 7: a role that doesn't require 2FA and hasn't enrolled logs in
// directly (2FA optional, not enrolled) — unchanged 200 shape.
// ================================================================

#[sqlx::test]
async fn viewer_login_returns_access_directly(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "viewer").await?;
    let router = support::router(pool);

    let (status, body) = login(&router, &account.email).await;

    assert_eq!(status, StatusCode::OK, "body={body}");
    assert!(body["access_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));
    assert!(body["refresh_token"]
        .as_str()
        .is_some_and(|s| !s.is_empty()));
    assert_eq!(body["role"], "viewer");
    assert!(body.get("enroll_required").is_none());
    assert!(body.get("twofa_required").is_none());
    Ok(())
}

// ================================================================
// Scenario 8: an enrollment_token / challenge_token cannot authorize a
// normal protected route.
// ================================================================

#[sqlx::test]
async fn purpose_tokens_cannot_access_protected_routes(pool: PgPool) -> sqlx::Result<()> {
    let account = seed_account(&pool, "admin").await?;
    let router = support::router(pool);

    // enrollment_token
    let (_status, body) = login(&router, &account.email).await;
    let enrollment_token = body["enrollment_token"]
        .as_str()
        .expect("enrollment_token")
        .to_owned();
    let status = get_status_with_bearer(&router, "/v1/secure-mode", &enrollment_token).await;
    assert_eq!(
        status,
        StatusCode::UNAUTHORIZED,
        "an enrollment_token must not authorize GET /v1/secure-mode"
    );

    // challenge_token (needs a confirmed account first)
    let (_secret, _backup_codes) = enroll_and_confirm(&router, &account).await;
    let (_status2, body2) = login(&router, &account.email).await;
    let challenge_token = body2["challenge_token"]
        .as_str()
        .expect("challenge_token")
        .to_owned();
    let status2 = get_status_with_bearer(&router, "/v1/secure-mode", &challenge_token).await;
    assert_eq!(
        status2,
        StatusCode::UNAUTHORIZED,
        "a challenge_token must not authorize GET /v1/secure-mode"
    );
    Ok(())
}
