[package]
name = "secureprompt-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "secureprompt_api"
path = "src/lib.rs"

[[bin]]
name = "secureprompt-api"
path = "src/main.rs"

[dependencies]
secureprompt-common = { path = "../secureprompt-common" }
tokio = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
hex = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
percent-encoding = { workspace = true }
sha2 = { workspace = true }
tokio-stream = { workspace = true }
async-stream = { workspace = true }
futures-util = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
failsafe = { workspace = true }
clickhouse = { workspace = true }
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }
password-hash = { workspace = true }
deadpool-redis = { workspace = true }
aes-gcm = { workspace = true }
rand = { workspace = true }
dashmap = { workspace = true }
oauth2 = { workspace = true }
gcp_auth = { workspace = true }
totp-rs = { workspace = true }
sp-license = { workspace = true }
ed25519-dalek = { version = "2", features = ["rand_core"] }

[lints]
workspace = true

[dev-dependencies]
sqlx = { workspace = true }
rand = "0.8"
