apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secureprompt.fullname" . }}-api
  labels:
    {{- include "secureprompt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "secureprompt.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "secureprompt.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "secureprompt.fullname" . }}-secrets
                  key: database-url
                  optional: true
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "secureprompt.fullname" . }}-secrets
                  key: redis-url
                  optional: true
