{{- if .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secureprompt.fullname" . }}-qdrant-pvc
  labels:
    {{- include "secureprompt.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.qdrant.persistence.storageClass }}
  storageClassName: {{ .Values.qdrant.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
{{- end }}
