apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secureprompt.fullname" . }}-worker
  labels:
    {{- include "secureprompt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "secureprompt.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "secureprompt.fullname" . }}-worker
      {{- if and .Values.serviceMesh.enabled (eq .Values.serviceMesh.provider "linkerd") }}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.global.imageRegistry | default "" }}{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "secureprompt.fullname" . }}-secrets
                  key: database-url
                  optional: true
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "secureprompt.fullname" . }}-secrets
                  key: redis-url
                  optional: true
