apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    editable: false
    jsonData:
      server: "${CLICKHOUSE_HOST}"
      port: 8123
      username: "${CLICKHOUSE_USER}"
      defaultDatabase: secureprompt
      tlsSkipVerify: true
    secureJsonData:
      password: "${CLICKHOUSE_PASSWORD}"
